---
apiVersion: v1
kind: Service
metadata:
  name: sp-content-processing
  namespace: snackpost
spec:
  selector:
    app: sp-content-processing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
