---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sp-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sp-bot
  template:
    metadata:
      labels:
        app: sp-bot
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: sp-bot
        image: ghcr.io/serdfxe/sp-bot:latest
        ports:
        - containerPort: 8000
        envFrom:
          - secretRef:
              name: sp-bot-secrets
        env:
          - name: WEBHOOK_URL
            value: "http://$(SP_BOT_SERVICE_IP):8000/webhook"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
