apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snackpost
  namespace: argocd
spec:
  project: snackpost
  source:
    repoURL: git@github.com:serdfxe/SnackPost.git
    targetRevision: HEAD
    path: iac/kubernetes
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true