apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: snackpost-certificate
  namespace: snackpost
spec:
  secretName: snackpost-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - bot.snackpost.ru