name: sp-bot-test

on:
  pull_request:
    paths:
      - 'sp-bot/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest
          pip install -r requirements.txt

      - name: Run black linting
        run: black --check sp-bot/

      - name: Build Docker image
        run: docker build -t sp-bot-test -f iac/images/sp-bot/Dockerfile .

      - name: Run tests in Docker
        run: docker run --rm sp-bot-test pytest /app/sp-bot/
