name: sp-scraper-deploy

on:
  push:
    branches: [ main, master ]
    paths:
      - 'sp-scraper/**'

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/sp-scraper

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t $DOCKER_IMAGE:${{ github.sha }} -t $DOCKER_IMAGE:latest -f Dockerfile .
        docker push $DOCKER_IMAGE:${{ github.sha }}
        docker push $DOCKER_IMAGE:latest

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git
        git push
